-- Deterministic demo data. Fixed ids, texts and dates (UTC), four weeks of work.
-- Reloading it always ends in exactly this state: TRUNCATE also clears rows added by tests.
truncate review_issues, reviews, responses, user_brands, issue_types, brands, users restart identity cascade;

-- Two Team Leads who split the brands (both cover Lumen Home), three Specialists on two brands each.
insert into users (id, name, role) values
  ('marta-vidal', 'Marta Vidal', 'team_lead'),
  ('nuria-costa', 'Nuria Costa', 'team_lead'),
  ('dani-ortega', 'Dani Ortega', 'specialist'),
  ('leo-martin',  'Leo Martin',  'specialist'),
  ('priya-shah',  'Priya Shah',  'specialist');

-- Three brands that want clearly different replies.
insert into brands (id, name, guidelines) values
  ('voltra', 'Voltra Scooters',
   'Technical product. Diagnose before offering a return or refund: ask for the model and what the display shows, then walk through the matching troubleshooting step. Half the complaints are usage issues. Friendly and precise; explain any jargon.'),
  ('boxwell', 'Boxwell Packaging',
   'B2B commodity supplier. Fast and exact: three lines or fewer, quote the order number, quantities and dates. No small talk, no emojis.'),
  ('lumen', 'Lumen Home',
   'Home decor. Warm and personal: use the customer''s name and acknowledge the trouble. Always check the order history before promising anything.');

insert into user_brands (user_id, brand_id) values
  ('marta-vidal', 'voltra'),  ('marta-vidal', 'lumen'),
  ('nuria-costa', 'boxwell'), ('nuria-costa', 'lumen'),
  ('dani-ortega', 'voltra'),  ('dani-ortega', 'boxwell'),
  ('leo-martin',  'voltra'),  ('leo-martin',  'lumen'),
  ('priya-shah',  'boxwell'), ('priya-shah',  'lumen');

-- What can be wrong with a reply, taken from the team lead's own words. Critical = loses accounts.
insert into issue_types (code, label, critical, sort_order) values
  ('wrong-information', 'Wrong product information',     true,  1),
  ('skipped-procedure', 'Skipped brand procedure',       true,  2),
  ('no-order-history',  'Did not check order history',   true,  3),
  ('wrong-question',    'Answered a different question', false, 4),
  ('not-resolved',      'Customer will write again',     false, 5),
  ('tone',              'Tone wrong for the brand',      false, 6),
  ('too-long',          'Too long for the brand',        false, 7);

insert into responses (id, brand_id, specialist_id, subject, customer_message, response_text, sent_at, source) values
  -- Voltra Scooters: diagnose first.
  ('vo-101', 'voltra', 'dani-ortega', 'Scooter will not turn on after charging',
   'I charged my Voltra S2 all night and now it will not turn on at all. I need it for work tomorrow.',
   'Hi, sorry about that! I have created a return label for you, just send the scooter back and we will refund you.',
   '2026-09-01 08:40:00+00', 'seed'),
  ('vo-102', 'voltra', 'leo-martin', 'Error E21 on the display',
   'My S3 shows E21 and the motor cuts out after a few seconds.',
   'Hi Ana, E21 means the brake sensor thinks the brake is pressed. Please check that both brake levers spring back fully, then hold the power button for 10 seconds to reset. If E21 comes back, send me a short video of the levers and I will arrange a repair under warranty.',
   '2026-09-02 10:15:00+00', 'seed'),
  ('vo-103', 'voltra', 'dani-ortega', 'Battery range dropped to 10 km',
   'My S2 used to do 35 km and now it barely does 10. It is 8 months old.',
   'That is normal, all batteries lose range over time. You can buy a new battery in our shop.',
   '2026-09-08 09:05:00+00', 'seed'),
  ('vo-104', 'voltra', 'leo-martin', 'Rear brake squeaks',
   'The rear brake squeaks every time I stop. Is it dangerous?',
   'Hi Tom, great question, and thanks for reaching out to us today! A squeak usually means the brake pad has a little dust or oil on it, which is very common, especially after riding in wet conditions or on dusty roads, and it is not dangerous in itself. Clean the disc with isopropyl alcohol and a clean cloth. If the squeak continues after that, the pads may need adjusting, and our guide at voltra.help/brakes walks you through it step by step.',
   '2026-09-09 14:30:00+00', 'seed'),
  ('vo-105', 'voltra', 'dani-ortega', 'Folding latch feels loose',
   'The folding latch on my S3 wobbles when I ride.',
   'Hi Sam, thanks for flagging it. Which model do you have, and does the wobble come from the latch or the stem? On the S3 the latch has a tension screw under the lever: tighten it a quarter turn with the 4 mm key from the box. If it still wobbles, send me a photo and I will book a check.',
   '2026-09-15 11:20:00+00', 'seed'),
  ('vo-106', 'voltra', 'leo-martin', 'App will not pair with the scooter',
   'The Voltra app keeps saying "no scooter found".',
   'Hi Jo, the app only finds the scooter when it is switched on and not paired to another phone. Turn the scooter on, then in the app go to Settings > Forget device and scan again. That fixes it in almost every case; if not, tell me the app version and I will dig in.',
   '2026-09-22 16:45:00+00', 'seed'),
  ('vo-107', 'voltra', 'dani-ortega', 'Can I ride in the rain?',
   'Is the S2 waterproof? It rains a lot here.',
   'Hi Kim, the S2 is rated IP54: light rain and puddles are fine, but avoid heavy rain and never wash it with a hose. Dry the deck and charging port before charging.',
   '2026-09-24 09:10:00+00', 'seed'),

  -- Boxwell Packaging: fast and exact.
  ('bx-201', 'boxwell', 'priya-shah', 'Quote for 5,000 mailer boxes',
   'Please quote 5,000 mailer boxes, size M, white, delivery to Leeds.',
   'Quote Q-4410: 5,000 mailer boxes M, white, 0.38 GBP each, 1,900 GBP total. Delivery to Leeds in 5 working days. Valid until 30 September.',
   '2026-09-01 09:00:00+00', 'seed'),
  ('bx-202', 'boxwell', 'dani-ortega', 'Delivery date for PO 7781',
   'When will PO 7781 arrive?',
   'Hi there!! 😊 Thanks so much for getting in touch, we really appreciate your business. I had a look and it seems like your order is doing great and should be with you soon, probably sometime next week if everything goes well with the carrier. Have a lovely day!',
   '2026-09-03 13:25:00+00', 'seed'),
  ('bx-203', 'boxwell', 'priya-shah', 'Invoice shows the wrong quantity',
   'Invoice INV-3302 charges 2,000 units but we only received 1,500.',
   'The quantity on INV-3302 is correct, it matches your order.',
   '2026-09-09 10:40:00+00', 'seed'),
  ('bx-204', 'boxwell', 'dani-ortega', 'Pallet damaged on arrival',
   'One pallet of order 8120 arrived crushed. 300 boxes unusable.',
   'Sorry. Replacement for 300 boxes (order 8120) ships tomorrow, arrives Thursday 17 September. No need to return the damaged ones.',
   '2026-09-10 15:05:00+00', 'seed'),
  ('bx-205', 'boxwell', 'priya-shah', 'Lead time for custom printed boxes',
   'What is the lead time for 10,000 boxes with our logo printed?',
   'Standard delivery for stock boxes is 3 to 5 working days anywhere in the UK.',
   '2026-09-16 08:55:00+00', 'seed'),
  ('bx-206', 'boxwell', 'dani-ortega', 'Repeat last month''s order',
   'Same as order 8120 please, delivery next Tuesday.',
   'Done: order 8390, same items as 8120 (2,000 boxes L), delivery Tuesday 29 September.',
   '2026-09-23 10:10:00+00', 'seed'),
  ('bx-207', 'boxwell', 'priya-shah', 'Minimum order for packing tape',
   'What is the minimum order for branded tape?',
   'Minimum 36 rolls. Branded tape ships in 10 working days after artwork approval.',
   '2026-09-25 12:00:00+00', 'seed'),

  -- Lumen Home: warm, and check the order history.
  ('lu-301', 'lumen', 'leo-martin', 'Lamp arrived with a cracked shade',
   'The glass shade of my Halo lamp arrived cracked. I am so disappointed, it was a gift.',
   'Hi Maria, I am so sorry, what a disappointing way to receive a gift. I have sent a new shade by express delivery, it arrives Thursday. There is no need to send the cracked one back.',
   '2026-08-31 17:20:00+00', 'seed'),
  ('lu-302', 'lumen', 'priya-shah', 'Where is my sofa?',
   'My sofa was due last week and I have heard nothing.',
   'Your sofa is on its way and will arrive soon.',
   '2026-09-02 09:30:00+00', 'seed'),
  ('lu-303', 'lumen', 'leo-martin', 'Rug colour is different from the photo',
   'The Oslo rug looks grey, not the sand colour in the photo.',
   'Colours can look different on screens. This is not a fault.',
   '2026-09-08 12:15:00+00', 'seed'),
  ('lu-304', 'lumen', 'priya-shah', 'Change my delivery address',
   'I moved last week, can you send order L-5521 to my new flat?',
   'Hi Chris, congratulations on the new flat! I checked order L-5521: it has not shipped yet, so I have updated the address to the one you sent. You will get a new confirmation email in a few minutes.',
   '2026-09-14 15:40:00+00', 'seed'),
  ('lu-305', 'lumen', 'leo-martin', 'Missing screws for the bookshelf',
   'The bag of screws was missing from my bookshelf box.',
   'Hi Noor, sorry about that, I know how frustrating it is to be stuck mid-assembly. A full screw kit is on its way and should arrive in 2 days.',
   '2026-09-17 10:05:00+00', 'seed'),
  ('lu-306', 'lumen', 'priya-shah', 'Returning a mirror',
   'The mirror is too big for the hallway. Can I return it?',
   'Hi Alex, of course. I checked your order and you are within the 30-day window. I have emailed you a free return label; once we receive the mirror the refund takes 3 to 5 days.',
   '2026-09-21 14:25:00+00', 'seed'),
  ('lu-307', 'lumen', 'leo-martin', 'Gift wrapping for an order',
   'Can you gift wrap order L-6010?',
   'Hi Sofia, lovely idea! I have added gift wrapping to order L-6010 at no charge.',
   '2026-09-24 11:30:00+00', 'seed');

-- 15 reviewed, 6 pending. Every score 1-5 appears; Voltra improves after coaching in week 2.
insert into reviews (id, response_id, brand_id, reviewer_id, score, feedback, created_at, updated_at) values
  ('rv-01', 'vo-101', 'voltra', 'marta-vidal', 2,
   'You went straight to a refund. For Voltra we diagnose first: a scooter that will not turn on after a full charge is usually the battery lock switch. Ask for the model and what the display shows, then the reset steps. The customer needs it for work tomorrow, a return does not help that.',
   '2026-09-02 09:00:00+00', '2026-09-02 09:00:00+00'),
  ('rv-02', 'vo-102', 'voltra', 'marta-vidal', 5,
   'This is the reply I show new joiners: explains the code, gives a safe step, and has a clear next step if it fails.',
   '2026-09-03 08:30:00+00', '2026-09-03 08:30:00+00'),
  ('rv-03', 'vo-103', 'voltra', 'marta-vidal', 1,
   'This is wrong: losing more than 30% of range in the first 12 months is covered by the battery warranty. Telling the customer it is normal and selling them a battery is how we lose Voltra. Please reread the warranty page and follow up with this customer today.',
   '2026-09-09 08:45:00+00', '2026-09-09 08:45:00+00'),
  ('rv-04', 'vo-104', 'voltra', 'marta-vidal', 4,
   'Correct diagnosis and safe advice. It could be half as long: lead with "not dangerous" and the cleaning step.',
   '2026-09-10 09:15:00+00', '2026-09-10 09:15:00+00'),
  ('rv-05', 'vo-105', 'voltra', 'marta-vidal', 4,
   'Big improvement: you asked for the model and gave the right fix before anything else. Keep doing this.',
   '2026-09-16 10:00:00+00', '2026-09-16 10:00:00+00'),
  ('rv-06', 'vo-106', 'voltra', 'marta-vidal', 5,
   'Clear cause, one simple fix, and you asked for the app version if it fails. Nothing to change.',
   '2026-09-23 08:20:00+00', '2026-09-23 08:20:00+00'),

  ('rv-07', 'bx-201', 'boxwell', 'nuria-costa', 5,
   'Perfect Boxwell reply: quote number, price, total, delivery and validity in three lines.',
   '2026-09-01 15:00:00+00', '2026-09-01 15:00:00+00'),
  ('rv-08', 'bx-202', 'boxwell', 'nuria-costa', 2,
   'Boxwell buyers want the date, not warmth. No emojis, no small talk, and "probably next week" is not an answer: check the carrier and give the exact date.',
   '2026-09-04 09:10:00+00', '2026-09-04 09:10:00+00'),
  ('rv-09', 'bx-203', 'boxwell', 'nuria-costa', 1,
   'The order history shows a short delivery of 500 units on this order. We told the customer the wrong thing about their own invoice. Issue a credit note for 500 units and apologise.',
   '2026-09-10 08:30:00+00', '2026-09-11 09:00:00+00'),
  ('rv-10', 'bx-204', 'boxwell', 'nuria-costa', 4,
   'Fast and exact, with order number and date. Fine to skip the return here.',
   '2026-09-11 10:20:00+00', '2026-09-11 10:20:00+00'),
  ('rv-11', 'bx-205', 'boxwell', 'nuria-costa', 3,
   'Short and clear, but it answers stock delivery, not custom print lead time (15 working days after artwork approval). Read the question twice.',
   '2026-09-17 09:40:00+00', '2026-09-17 09:40:00+00'),

  ('rv-12', 'lu-301', 'lumen', 'marta-vidal', 4,
   'Warm, uses her name and fixes it in one message. Next time mention the order number so she can track it.',
   '2026-09-01 09:30:00+00', '2026-09-01 09:30:00+00'),
  ('rv-13', 'lu-302', 'lumen', 'nuria-costa', 1,
   'The order history shows this sofa was cancelled by the warehouse on 28 August. Always check the history before promising a delivery. The customer will write again, and rightly.',
   '2026-09-03 10:00:00+00', '2026-09-03 10:00:00+00'),
  ('rv-14', 'lu-303', 'lumen', 'nuria-costa', 3,
   'Technically right, but cold for Lumen. Acknowledge the disappointment and offer the free return or a swatch.',
   '2026-09-09 11:00:00+00', '2026-09-09 11:00:00+00'),
  ('rv-15', 'lu-304', 'lumen', 'marta-vidal', 4,
   'You checked the order history before promising anything, exactly right. Warm and clear.',
   '2026-09-15 08:50:00+00', '2026-09-15 08:50:00+00');

insert into review_issues (review_id, issue_code) values
  ('rv-01', 'skipped-procedure'), ('rv-01', 'not-resolved'),
  ('rv-03', 'wrong-information'), ('rv-03', 'skipped-procedure'),
  ('rv-04', 'too-long'),
  ('rv-08', 'tone'), ('rv-08', 'too-long'), ('rv-08', 'not-resolved'),
  ('rv-09', 'no-order-history'), ('rv-09', 'wrong-information'),
  ('rv-11', 'wrong-question'),
  ('rv-13', 'no-order-history'), ('rv-13', 'not-resolved'),
  ('rv-14', 'tone');
